variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "port" {}
variable "ssh_ingress_cidr" {}
variable "sg_ingress_cidr" {}
variable "component" {}
variable "subnet_ids" {}
variable "ami" {}
variable "zone_id" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "private_alb_name" {}
variable "private_lb_listener" {}
variable "public_alb_name" {}
variable "public_lb_listener" {}
variable "priority" {}

